#!/bin/bash

# timezone
timedatectl set-timezone Asia/Taipei

# basic packages
sudo apt-get update
sudo apt-get install -y curl vim

# git
sudo add-apt-repository -y ppa:git-core/ppa
sudo apt-get update
sudo apt-get install -y git
git config --global core.editor "vim"
git config --global user.name "HarkuLi"
git config --global user.email "harku85697708@hotmail.com"

# zsh
sudo apt-get install -y zsh
## oh my zsh
sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
perl -i -pe "s/ZSH_THEME=.*/ZSH_THEME=geoffgarside/g" ~/.zshrc
source ~/.zshrc
